version: '3.8'

services:
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: travel_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel_network

  
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/auth_service
      AUTH_SERVICE_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - travel_network

 
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/user_service
      USER_SERVICE_PORT: 8002
      AUTH_SERVICE_URL: http://auth-service:8001
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - auth-service
    networks:
      - travel_network

  
  trip-service:
    build:
      context: .
      dockerfile: trip-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/trip_service
      TRIP_SERVICE_PORT: 8003
      AUTH_SERVICE_URL: http://auth-service:8001
      USER_SERVICE_URL: http://user-service:8002
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - auth-service
      - user-service
    networks:
      - travel_network

  
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/notification_service
      NOTIFICATION_SERVICE_PORT: 8004
      AUTH_SERVICE_URL: http://auth-service:8001
    ports:
      - "8004:8004"
    depends_on:
      - postgres
      - auth-service
    networks:
      - travel_network

  
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    environment:
      API_GATEWAY_PORT: 8000
      AUTH_SERVICE_URL: http://auth-service:8001
      USER_SERVICE_URL: http://user-service:8002
      TRIP_SERVICE_URL: http://trip-service:8003
      NOTIFICATION_SERVICE_URL: http://notification-service:8004
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service
      - trip-service
      - notification-service
    networks:
      - travel_network

networks:
  travel_network:
    driver: bridge

volumes:
  postgres_data: